name: 'Hello World JS Action'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'node16'
  main: 'index.js'