# .github/workflows/build-and-test.yml

name: Build and Test
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [${{ inputs.node-version }}]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
