# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-job:
    uses: ./.github/workflows/build-and-test.yml
    with:
      node-version: '16'