name: Chained Jobs Workflow

on: 
    push:
        branches: [ main,f1,f2 ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      random_number: ${{ steps.generate_random.outputs.random_number }}
    steps:
    - id: generate_random
      name: Generate a random number
      run: echo "::set-output name=random_number::$(echo $((RANDOM % 100)))"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    outputs:
      incremented_value: ${{ steps.increment.outputs.incremented_value }}
    steps:
    - id: increment
      name: Increment value from job1 by 10
      run: echo "::set-output name=incremented_value::$(echo $((${{ needs.job1.outputs.random_number }} + 10)))"

  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - name: Increment value from job2 by 20
      run: |
        ${{ format('echo "Final value: $(echo $(%d + 20))"', needs.job2.outputs.incremented_value) }}
