name: Chained Increment Workflow

on:
  push:
    branches: [ main, f1, f2 ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      random_number: ${{ steps.generate_random.outputs.random_number }}
    steps:
      - id: generate_random
        run: |
          random_number=$((RANDOM % 100))
          echo "random_number=$random_number" >> $GITHUB_ENV
          echo "Random number (job1): $random_number"

  job2:
    needs: job1
    uses: ./.github/workflows/reusable-component.yml
    with:
      number: ${{ needs.job1.outputs.random_number }}

  job3:
    needs: job2
    uses: ./.github/workflows/reusable-component.yml
    with:
      number: ${{ needs.job2.outputs.incremented_number }}
