name: Chained Increment Workflow

on:
  push:
    branches: [ main, f1, f2 ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      random_number: ${{ steps.generate_random.outputs.random_number }}
    steps:
      - id: generate_random
        run: |
          random_number=$((RANDOM % 100))
          echo "random_number=$random_number" >> $GITHUB_ENV
          echo "Random number (job1): $random_number"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    outputs:
      incremented_value: ${{ steps.increment.outputs.incremented_value }}
    steps:
      - id: increment
        run: |
          incremented_value=$((${{ needs.job1.outputs.random_number }} + 10))
          echo "incremented_value=$incremented_value" >> $GITHUB_ENV
          echo "Incremented value (job2): $incremented_value"

  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Increment value from job2 by 20
        run: |
          final_value=$((${{ needs.job2.outputs.incremented_value }} + 20))
          echo "Final value (job3): $final_value"
