name: Reusable Increment Job

on:
  workflow_call:
    inputs:
      number:
        required: true
        type: number
    outputs:
      incremented_number:
        description: "The incremented number"
        value: ${{ jobs.increment.outputs.incremented_number }}

jobs:
  increment:
    runs-on: ubuntu-latest
    outputs:
      incremented_number: ${{ steps.increment.outputs.incremented_number }}
    steps:
      - id: increment
        run: |
          incremented_number=$((${{ inputs.number }} + 10))
          echo "incremented_number=$incremented_number" >> $GITHUB_ENV
          echo "::set-output name=incremented_number::$incremented_number"
